In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Datasets/Redmi Fuel Band Record Tracker (Fitbit Dataset)/Activity_Dataset_V1.csv')

In [13]:
df.describe()

,Unnamed: 0,distance,time,calories,total_steps,avg_speed,avg_cadence,max_cadence,avg_heart_rate,max_heart_rate,min_heart_rate,vo2_max(%),aerobic(%),anaerobic(%),intensive(%),light(%),cal/dist ratio
count,1000.000000,1000.000000,1000.000000,1000.000000,554.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,499.500000,5.243620,71.166000,286.310000,4081.119134,19.765780,107.457870,199.821910,116.282000,136.655000,95.909000,22.322000,24.077000,17.899000,36.236000,50.947000,79.079086
std,288.819436,2.649774,29.341359,156.278511,1865.429141,10.871037,54.312209,85.397007,20.573679,39.739416,9.450504,12.941166,16.881115,26.864559,18.125254,28.211063,74.962200
min,0.000000,1.000000,20.000000,10.000000,1571.000000,1.000000,10.130000,50.560000,82.500000,85.000000,80.000000,0.000000,0.000000,0.000000,5.000000,2.000000,1.008065
25%,249.750000,2.800000,45.000000,155.750000,2790.000000,10.300000,62.530000,129.097500,97.000000,92.000000,88.000000,11.000000,0.000000,0.000000,21.000000,26.000000,28.178634
50%,499.500000,5.105000,71.000000,290.500000,3444.000000,19.395000,111.065000,198.800000,113.000000,124.000000,96.000000,22.000000,26.000000,7.000000,36.000000,51.000000,54.951700
75%,749.250000,7.542500,97.000000,415.250000,5028.000000,28.932500,153.605000,274.292500,136.500000,177.000000,104.000000,33.000000,40.000000,15.000000,52.000000,76.000000,102.179602
max,999.000000,9.990000,120.000000,550.000000,7618.000000,38.900000,199.780000,349.780000,150.500000,190.000000,111.000000,45.000000,50.000000,80.000000,67.000000,100.000000,461.403509

In [11]:
df['cal/dist ratio'] = df['calories'] / df['distance']

In [16]:
df[df['cal/dist ratio']<20].describe()

,Unnamed: 0,distance,time,calories,total_steps,avg_speed,avg_cadence,max_cadence,avg_heart_rate,max_heart_rate,min_heart_rate,vo2_max(%),aerobic(%),anaerobic(%),intensive(%),light(%),cal/dist ratio
count,178.000000,178.000000,178.000000,178.000000,96.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,545.106742,6.916966,72.898876,71.685393,4051.468750,19.810000,109.221292,190.050393,116.370787,137.342697,95.398876,23.415730,23.584270,18.308989,36.651685,51.550562,10.415360
std,288.386873,2.249840,30.627725,45.638990,1945.611158,10.931365,54.476666,87.985294,21.362889,40.092273,9.352688,13.585726,16.907732,27.566459,17.683087,27.566053,5.227151
min,0.000000,1.300000,20.000000,10.000000,1571.000000,1.100000,10.530000,51.450000,82.500000,85.000000,80.000000,0.000000,0.000000,0.000000,5.000000,2.000000,1.008065
25%,323.250000,5.460000,42.000000,34.000000,2790.000000,9.917500,63.687500,116.502500,96.625000,92.000000,88.000000,11.000000,0.000000,0.000000,22.000000,29.250000,5.948454
50%,567.500000,7.470000,78.000000,63.000000,3444.000000,19.055000,113.980000,188.490000,111.250000,124.000000,95.000000,22.500000,26.000000,7.000000,36.000000,53.000000,10.494580
75%,784.750000,8.707500,99.000000,102.500000,5028.000000,29.717500,155.910000,271.065000,138.375000,177.000000,103.000000,35.000000,38.000000,15.000000,52.750000,74.500000,14.457156
max,998.000000,9.980000,120.000000,188.000000,7618.000000,37.990000,199.670000,349.660000,150.500000,190.000000,111.000000,45.000000,50.000000,80.000000,67.000000,100.000000,19.915254